builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
    main: ./

archives:
  - format: binary
    name_template: '{{ .Binary }}'

checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_checksums.txt'

